version: "3.3"
services:
  app:
    image: mattermost/focalboard:latest
    container_name: focalboard
    restart: always
    volumes:
      - ${APP_DATA_DIR}/data:/opt/focalboard/data
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000
    labels:
      - com.umbrel.app-id=${APP_ID}
      - com.umbrel.version=${APP_VERSION}

  app_proxy:
    image: nginx:1.23-alpine
    restart: always
    environment:
      - VIRTUAL_HOST=${APP_HIDDEN_SERVICE}
      - VIRTUAL_PORT=80
    volumes:
      - ${APP_DATA_DIR}/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

networks:
  default:
    external: true
    name: umbrel_network
