version: "3.3"
services:
  app:
    image: mattermost/focalboard:latest
    container_name: focalboard
    ports:
      - "$APP_PORT:8000"
    volumes:
      - ${APP_DATA_DIR}/data:/opt/focalboard/data
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000
    restart: always
    networks:
      - default
    labels:
      - com.umbrel.app-id=${APP_ID}
      - com.umbrel.version=${APP_VERSION}

networks:
  default:
    name: umbrel_network
    external: true
