version: "3.7"

services:
  spotube:
    image: spotube/spotube:latest
    container_name: spotube
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/data
    ports:
      - ${APP_SPOTUBE_PORT:-8157}:8157
    networks:
      - umbrel

networks:
  umbrel:
    external: true
