services:
  spotube:
    image: ghcr.io/linuxserver/spotube:latest
    container_name: spotube
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/data:/data
    ports:
      - ${APP_SPOTUBE_PORT:-8157}:8157
